version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=kwizz
      - POSTGRES_PASSWORD=kwizz
      - POSTGRES_DB=kwizz
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  api:
    build: ./KwizzApi
    links:
      - db:postgres-db
    ports:
      - "5000:5000"

  site:
    build: ./site
    ports:
      - "8000:80"
    environment:
      - WEB_DOCUMENT_ROOT=/var/web/public
      - API_BASE=localhost:5000
